name: Go Checks

on:
  push:
    branches: [ "main" ]

permissions: {}

jobs:

  codecov:
    name: Push to main test
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: go test ./...

    - name: Update coverage report
      uses: ncruces/go-coverage-report@aa507d98fb11c2b4dffa1b731e0786f50fd8ec93 # v0.3.1
      with:
        report: true
        chart: true
        amend: true
      if: github.event_name == 'push'
      continue-on-error: true
